---
kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "flask-webapp-color-ci-pipeline"
  namespace: python-color-app-test
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/SlitiBrahim/flask-webapp-color.git'
      ref: test
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
---
kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "flask-webapp-color-ci-pipeline"
  namespace: python-color-app-staging
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/SlitiBrahim/flask-webapp-color.git'
      ref: staging
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
---
kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "flask-webapp-color-ci-pipeline"
  namespace: python-color-app-prod
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/SlitiBrahim/flask-webapp-color.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
