apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: flask-webapp-color
  namespace: python-color-app-test
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: flask-webapp-color
  namespace: python-color-app-staging
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: flask-webapp-color
  namespace: python-color-app-prod

