apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-color-app-staging
  namespace: gitops
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SlitiBrahim/flask-webapp-color-argocd
    path: staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: python-color-app-staging
